name: build on testbranch
# build file using github actions
# 
on:
  push:
    branches: [ maker99-test ]
#  pull_request:
#    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
        GCC_URL: https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        GCC_PATH: $HOME/arm-gcc-toolchain
        GCC_VERSION: 9-2019-q4
        GCC: arm-none-eabi-gcc
        
    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        # GNU Embedded Toolchain for Arm release name, in the V-YYYY-qZ format (e.g. "9-2019-q4")
        release: $GCC_VERSION
        # Directory to unpack GCC to. Defaults to a temporary directory.
        directory: $GCC_PATH
        
    - name: show config
      run: |
        chmod 755 *.sh
        ls -al
      
    - name: check build environment
      run: |    
        pwd
        ls -al 
        printenv
        ls -al $GCC_PATH
        
    - name: check arm toolchain
      run: |
       $GCC --version

    - name: make it
      run: |
        echo $PATH
        echo make 
