name: build on testbranch
# build file using github actions
# 
on:
  push:
    branches: [ maker99-test ]
#  pull_request:
#    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
        GCC_URL: https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        
    steps:
    - uses: actions/checkout@v2
      
    - name: show config
      run: |
        ls -al
        chmod 755 *.sh
      
    - name: prepare build environment
      run: |    
        pwd
        mkdir -p arm-gcc-toolchain
        wget -nv  $GCC_URL -O./arm-gcc-toolchain/gcc.tar.bz2
        cd arm-gcc-toolchain
        ls -al
        tar -jxf gcc.tar.bz2 --strip=1
        ls -al 
        export PATH=$PWD/arm-gcc-toolchain/bin:$PATH
        echo "arm environment:"
        printenv
        ls -al arm-gcc-toolchain
        
        
    - name: check arm toolchain
      run: |
       arm-none-eabi-gcc --version

    - name: make it
      run: |
        echo $PATH
        echo make 
